### PR TITLE
Enable the IN clause to also compare the value of single-pair structs

### PR DESCRIPTION
**Pull request by johnedquinn**
## Related Issue
Related to #524

## Description
Allows the IN clause to compare the value of single-pair structs, to maintain compatibility with SQL-92. To do this, it is necessary to make two changes:
- If the rightOp is already computed as a sequence of single-pair structs (where each pair's value is a literal), we can use the optimized approach and immediately compare with that value.
- If the rightOp is not computed (for example: another SELECT returning a bag/list of structs, or a bag of structs with pairs that contain un-evaluated values), then we need to evaluate.

### Examples

```sql
SELECT age FROM << { 'name': 'John', 'age': 22 } >> WHERE name IN (SELECT name FROM <<{ 'name': 'John' }>>)
```
should result in:
```ion
<<
  { age: 22 }
>>
```
## Notice
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dlurton** [comment]
This change only applies to `EvaluatingCompiler`.  Since we're intending to remove the `EvaluatingCompiler` at some point and its replacement isn't complete yet, there are two options:

1. Make this change in `EvaluatingCompiler` **and** its replacement (`PhysicalBexprToThunkConverter`, introduced in #592 and will be merged to `main` today if all goes well). 
2. Make this change in only `PhysicalBexprToThunkConverter`, which means this fix will have limited applicability until the `PhysicalBexprToThunkConverter` is complete and `EvaluatingCompiler` is removed.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt [hunk 1]
```diff
@@ -743,6 +747,13 @@ internal class EvaluatingCompiler(
             // NOTE: we cannot use a [HashSet<>] here because [ExprValue] does not implement [Object.hashCode] or
             // [Object.equals].
             val precomputedLiteralsMap = values
+                .asSequence()
+                .map { value ->
+                    when (value) {
+                        is PartiqlAst.Expr.Struct -> if (value.isSingleValueOptimizedStruct()) value.fields[0].second else value
+                        else -> value
+                    }
+                }
```
Comment (dlurton) [inline lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:756]: What's the use-case for this optimization?  Has this been reported by a customer as being slow?  If not, I would avoid optimizing this as it may be premature.  The other optimizations here were added as a direct result of customer feedback.

File: cli/test/org/partiql/cli/CliTest.kt [hunk 2]
```diff
@@ -155,6 +155,30 @@ class CliTest {
...
+        makeCli(
+            query = "SELECT age FROM << { 'name': 'John', 'age': 22 } >> WHERE name IN (SELECT name FROM <<{ 'name': 'john' }>>)",
+            output = FileOutputStream(testFile),
+            outputFormat = OutputFormat.ION_TEXT
+        ).run()
+        val actual = testFile.bufferedReader().use { it.readText() }
+
+        assertEquals("\n", actual)
+    }
+
```
Comment (dlurton) [inline cli/test/org/partiql/cli/CliTest.kt:181]: Please add these tests to `EvaluatorTestSuite`--instead they are not needed here if the exist there.  

Also, please add a simpler versions of the test case which will be easier to understand the actual feature being tested:

These all must return `true`:

```
`foo` in << { 'foo': } >>
`foo` in [ { 'foo': } ]
`foo` in SEXP({ 'foo': })
```
And these must all return false:

```
`bar` in << { 'foo': } >>
`bar` in [ { 'foo': } ]
`bar` in SEXP({ 'foo': })
```

File: cli/test/org/partiql/cli/CliTest.kt [hunk 3]
```diff
@@ -155,6 +155,30 @@ class CliTest {
...
+    fun withSelectInButEmpty() {
+        makeCli(
+            query = "SELECT age FROM << { 'name': 'John', 'age': 22 } >> WHERE name IN (SELECT name FROM <<{ 'name': 'john' }>>)",
+            output = FileOutputStream(testFile),
+            outputFormat = OutputFormat.ION_TEXT
+        ).run()
+        val actual = testFile.bufferedReader().use { it.readText() }
+
+        assertEquals("\n", actual)
+    }
```
Comment (dlurton) [inline cli/test/org/partiql/cli/CliTest.kt:180]: Anyway, looking again at your other tests, I don't think there's a need to test the CLI separately from the `EvaluatingCompilerInTests`.

File: lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt (hunk 1 above)
Comment (johnedquinn) [reply lang/src/org/partiql/lang/eval/EvaluatingCompiler.kt:756]: ACK. I can modify. Thanks!

File: cli/test/org/partiql/cli/CliTest.kt (hunk 3 above)
Comment (johnedquinn) [reply cli/test/org/partiql/cli/CliTest.kt:180]: ACK. I can remove. Thanks!

**Comment by johnedquinn** [comment]
> This change only applies to `EvaluatingCompiler`. Since we're intending to remove the `EvaluatingCompiler` at some point and its replacement isn't complete yet, there are two options:
> 
> 1. Make this change in `EvaluatingCompiler` **and** its replacement (`PhysicalBexprToThunkConverter`, introduced in [Add Plan Evaluator #592](https://github.com/partiql/partiql-lang-kotlin/pull/592) and will be merged to `main` today if all goes well).
> 2. Make this change in only `PhysicalBexprToThunkConverter`, which means this fix will have limited applicability until the `PhysicalBexprToThunkConverter` is complete and `EvaluatingCompiler` is removed.

@dlurton -- Since this is working on a feature branch off of main, do you think it would make sense to create a separate PR to add to `PhysicalBexprToThunkConverter`? Then, this one can be merged immediately on approval, and I can work on merging to the other branch? Unless, of course, the other branch is expected to merge by EOD. Then, I'll just park this, pull once other is merged, then add to `PhysicalBexprToThunkConverter ` and merge in the same PR later. Whatever works.

**Comment by dlurton** [comment]
@johnedquinn I am hoping it can be merged by EOD today but that will depend on getting the approval of @alancai98 

I would not make that separate PR due to the possibility of it being "inadvertently deprioritized".

**Comment by johnedquinn** [comment]
@dlurton -- ACK. I'll park this and wait for the merge to main.

**Action items**:
- once #612 is merged to main, I'll pull and add my changes for the new evaluator compiler

**Comment by johnedquinn** [comment]
Accidentally merged all of the new changes in main into this feature branch. Starting a new one to make it easier for reviewers. Following up with PR #621 .
